sonar.projectKey=jenkins-pipeline

sonar.host.url=http://localhost:9000
sonar.sources=src/main,src/test
sonar.language=java
sonar.java.binaries=target/classes  
sonar.login=sqa_778f609c2f2d47723cc3430abec89d88d31dfe6d
